### ISSUE TITLE
Milestone 1: Cobuild Rev 3

### ISSUE THREAD

**Issue by doitian** [doitian/ckb-dao-cobuild-poc#1]
- [x] Transfer CKB https://pudge.explorer.nervos.org/transaction/0x6f2f684fbc18031f8ca5d4dea4eb97535a221490a48a000bdf524549c574ee2d
- [x] Deposit DAO
- [x] Withdraw DAO Phase 1
- [x] Withdraw DAO Phase 2
- [x] Better Building Packet Presentation

Preview: https://ckb-dao-cobuild-poc.vercel.app/

## Building Workflow

- Use one of the function in [src/lib/cobuild/publishers.js](https://github.com/doitian/ckb-dao-cobuild-poc/blob/main/src/lib/cobuild/publishers.js) to build the transaction for apps.
- Use [src/lib/cobuild/lock-actions.js](https://github.com/doitian/ckb-dao-cobuild-poc/blob/main/src/lib/cobuild/lock-actions.js) to prepare `lockActions`.
- Apply `lockActions` by connecting to the wallet and store the signature. See more in https://github.com/doitian/ckb-dao-cobuild-poc/blob/main/src/app/accounts/%5Baddress%5D/sign-form.js
- Send tx
