### ISSUE TITLE
Milestone 2: DAO Papp

### ISSUE THREAD

**Issue by doitian** [doitian/ckb-dao-cobuild-poc#3]
- [x] Design ScriptInfo for DAO and demonstrate how to build transaction from a DAO ScriptInfo instance (a.k.a, a DAO Cobuild Action).
- [x] Use JoyID lock and WitnessArgs layout. This task cancels #2 .
- [x] Add an optional step to attach the DAO Cobuild Action as an extra witness at the position outside the number of input cells.
- [ ] #6
- [ ] #7
